export const ROUTES = {
  LOGIN: "/login",
  ACTIVE: "/active/:uid",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  NEW_PASSWORD: "/forgot-password/:uid",
  USER: {
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    PRODUCT_LIST: "/products",
    PRODUCT_DETAIL: "/products/:id",
    CART: "/cart",
    CHECKOUT: "/checkout",
    PROFILE: "/profile",
    USER_INFO: "/profile/user-info",
    ORDER_HISTORY: "/profile/order-history",
    FAVORITE_PRODUCTS: "/profile/favorite-products",
    CHANGE_PASSWORD: "/profile/change-password",
  },
  ADMIN: {
    DASHBOARD: "/admin",
    PRODUCT_LIST: "/admin/products",
    CREATE_PRODUCT: "/admin/products/create",
    UPDATE_PRODUCT: "/admin/products/:id/update",
    USER_MANAGE: "/admin/users",
    ORDER_MANAGE: "/admin/orders",
    COMMENT_MANAGE: "/admin/comments",
    CATEGORY_LIST: "/admin/categories",
    CREATE_CATEGORY: "/admin/categories/create",
    DELETE_CATEGORY: "/admin/categories/delete/:id",
    UPDATE_CATEGORY: "/admin/categories/:id/update",
    TYPE_LIST: "/admin/types",
    CREATE_TYPE: "/admin/types/create",
    UPDATE_TYPE: "/admin/types/:id/update",
  },
};
